// The keeper's remembered advice for each kind of monster, shown in the Journal once the
// insight is unlocked.

export const INSIGHT_TEXT: Record<string, string> = {
  rat: 'Rats. Keep your backs to a wall and they break quickly.',
  skeleton: 'Skeletons. Blunt weapons, and don\'t waste arrows on the ribs.',
  ghoul: 'Ghouls. Their claws numb you. Never fight one alone.',
  cultist: 'Cultists. Kill the one chanting first.',
  mimic: 'A mimic. Tell them to strike the chest first.',
  warden: 'The Crypt Warden. It is slow. Make it turn, and keep it turning.',
  sporeling: 'Sporelings. Cover your mouths. Fire if you have it.',
  spider: 'Cave spiders. Watch the ceiling, not the floor.',
  slime: 'Grey slime. Don\'t let it touch steel you want to keep.',
  troglodyte: 'Troglodytes. The stink is the worst of it. Push through.',
  myconid: 'Myconids. They talk through spores. Don\'t listen.',
  bloom: 'The Mother Bloom. Cut the roots, not the flower.',
  drowned: 'The drowned dead. They are slow on dry stone. Fight on the steps.',
  eels: 'Eels. Stay out of the water. That\'s all there is to it.',
  sahuagin: 'Sahuagin. They hunt in threes. Count them.',
  siren: 'A siren. Wax in the ears, and trust the one who can\'t hear her.',
  weird: 'Water weirds. Break the pool and they have nothing to be.',
  tidewight: 'The Tidewight. Salt, and keep it away from the water.',
  golem: 'Iron golems. Find the seam behind the knee.',
  imp: 'Fire imps. Cheap trouble. Don\'t chase them into the dark.',
  duergar: 'Duergar. They fight well and retreat better. Don\'t follow.',
  salamander: 'Salamanders. Their skin burns. Spears, not swords.',
  hound: 'Clockwork hounds. Jam the gears; the key is on the back.',
  anvilking: 'The Anvil King. It must stop to strike. Strike then.',
  horror: 'Flesh horrors. What cuts one, splits it. Burn it.',
  wraith: 'Wraiths. Only faith or silver. Keep the cleric close.',
  curseborn: 'Curse-born. They were people once. Don\'t let that slow your hand.',
  crawler: 'Vein crawlers. They follow the blood. Bind wounds quickly.',
  hollowknight: 'Hollow knights. The armour is empty. Hit what holds it together.',
  source: 'The Source. You never saw it. Nobody has. Yet.',
  ghost: 'Grave ghosts. They want to be remembered. Say their name.',
};
